package reidConnect.backend.enums;

public enum AcademicRank {
    PROFESSOR,

    DEPARTMENT_HEAD,

    SENIOR_LECTURER,

    LECTURER,
    LECTURER_PROBATIONARY,

    INSTRUCTOR_PERMANENT,

    SENIOR_LECTURER_ON_CONTRACT,
    LECTURER_ON_CONTRACT,
    ASSISTANT_LECTURER_TEMPORARY,
    INSTRUCTOR_TEMPORARY
}
