spring.application.name=rc-backend

spring.datasource.url=jdbc:${DATABASE_URL}
# spring.datasource.username=${DATABASE_USERNAME}
# spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# security.jwt.secret-key=t9Z7nX2RgY4PvBQjM1vWhkUsaLF8e0Cd
security.jwt.secret-key=${JWT_SECRET_KEY}
# JWT expiration time: 1 day
security.jwt.expiration-time=86400000
# spring.mail.username=udarapiumal0@gmail.com
spring.mail.username=${MAIL_USERNAME}
# spring.mail.password=yhzq bkhv oavo odor
spring.mail.password=${MAIL_PASSWORD}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# File upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Static resource serving (for serving uploaded images)
# Using relative path for better portability
spring.web.resources.static-locations=file:${UPLOAD_PATH}
spring.devtools.restart.enabled=false
